miku/app1/urls.py
from django.urls import path

from . import views

app_name = 'app1'

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    # path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
    path('inquiry/', views.contact_view, name="inquiry"),
]

miku/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('blog-detail/<int:pk>/', views.BlogDetail.as_view(), name="blog_detail"),
]

miku/miku/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('user/', include('user.urls')),
    path('accounts/', include('allauth.urls')),
]

miku/blog/models.py
from django.db import models


class BlogPost(models.Model):
    ''' Model Class
    '''
    title = models.CharField(max_length=200)
    content = models.TextField()
    posted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

miku/blog/views.py
import logging
from django.contrib import messages
from django.urls import reverse_lazy

from django.views import generic
from django.views.generic import ListView, DetailView
from .models import BlogPost


logger = logging.getLogger(__name__)


class IndexView(ListView):

    template_name = 'blog/index.html'
    context_object_name = 'orderby_records'
    queryset = BlogPost.objects.order_by('-posted_at')
    paginate_by = 5


class BlogDetail(DetailView):

    template_name = 'blog/post.html'
    model = BlogPost

miku/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Blog | Project Miku{% endblock %}
{% block content %}
<section>
  <div class="container">
    <h2 class="my-4">Blog</h2>
    <div class="row">
    <p>Blog your own site</p>
      <div class="col-md-10 col-lg-8 col-xl-7">
        {% for record in orderby_records %}
        <div class="post-preview">
          <a href="{% url 'blog:blog_detail' record.pk %}">
            <h2 class="post-title">
              {{ record.title }}</h2>
            <h3 class="post-subtitle">
              <span style="font-size : 14pt">
                {{ record.content| truncatechars:50}}
              </span>
            </h3>
          </a>
          <p class="post-meta">
          <a href="#">Django's Blog</a>
            Post at {{ record.posted_at }}
          </p>
        </div>

        <hr class="my-4" />
        {% endfor %}

        {% include "pagination.html" %}
      </div>
    </div>
  </div>
</section>
{% endblock %}

miku/templates/blog/post.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Blog | Project Miku{% endblock %}
{% block content %}
<section>
  <div class="container">
    <h2 class="my-4">{{ object.title }}</h2>
    <div class="row">
    <p>Blog your own site</p>
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="post-preview">
            <h2 class="post-title">
              {{ object.title }}</h2>
              <p>
                {{ object.content }}
              </p>
          <p class="post-meta">
            Post at {{ object.posted_at }}
          </p>
        </div>

        <div class="d-flex justify-content-end mb-4">
          <a class="btn btn-primary text-uppercase" href="#!">
            Older Posts ->
          </a>
        </div>
      </div>
    <div class="row">
    {% if user.is_authenticated %}
    {{ user.username }}
    {{ user.email }}
    {% else %}
    You are a guest.
    {% endif %}
    </div>
    </div>
  </div>
</section>
{% endblock %}