miku/app1/urls.py
from django.urls import path

from . import views

app_name = 'app1'

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    # path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
    path('inquiry/', views.contact_view, name="inquiry"),
]

miku/miku/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('user/', include('user.urls')),
    path('accounts/', include('allauth.urls')),
]

miku/user/urls.py
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
]

miku/templates/base.html
{% load static %}
{% load i18n %}
{% now "Y" as current_year %}
{% get_current_language as LANGUAGE_CODE %}
<!Doctype html>
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8" />
    <meta name="viewpoint" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="auther" content="" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href={% static 'assets/favicon.ico' %} />
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&family=Lora:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href={% static 'assets/favicon.ico' %} />
    <link rel="stylesheet" type="text/css" href="{% static 'css/my_css.css' %}" />
  </head>
  <body>
    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">Find your favorite!</h4>
              <p class="text-muted">
                This is a space for comment from site manager.
              </p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">{% trans "Contact" %}</h4>
              <ul class="list-unstyled">
              {% if user.is_authenticated %}
                <li><a href="#" class="text-white">{% trans "Hello" %}, {{ user.username }}!</a></li>
                <li><a href="{% url 'account_logout' %}" class="text-white">{% trans "Log Out" %}</a></li>
              {% else %}
                <li><a href="{% url 'account_signup' %}" class="text-white">{% trans "Sign Up" %}</a></li>
                <li><a href="{% url 'account_login' %}" class="text-white">{% trans "Log In" %}</a></li>
              {% endif %}
                <li><a href="{% url 'app1:inquiry' %}" class="text-white">{% trans "INQUIRY" %}</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
          <a href="{% url 'app1:index' %}" class="navbar-brand d-flex align-items-center">
            <strong>Hello World! You are {% if user.is_authenticated %}{{ user.username }}{% else %}a guest{% endif %}.</strong>
          </a>
          {% if user.is_authenticated %}<a href="{% url 'user:index' %}">{{ user.username }}</a>{% else %}a guest{% endif %}
          <button class="navbar-toggler"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#navbarHeader"
                  aria-controls="navbarHeader"
                  aria-expanded="false"
                  aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>
    <main>
      <ul class="messages" style="list-style: none;">
      {% if messages %}
        {% for message in messages %}
          <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {{ message }}
          </li>
        {% endfor %}
      {% endif %}
      </ul>
      {% block content %}{% endblock %}
    </main>
    <footer class="text-muted py-5">
      <div class="container">
        <p class="float-end mb-1">
          <a href="#">Back to top</a>
        </p>
        <p class="mb-1">
          Hello world is Copyright &copy; {{ current_year }} Project Miku
        </p>
      </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/6cf96fe5c4.js" crossorigin="anonymous"></script>
  </body>
</html>

miku/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Project Miku{% endblock %}
{% block content %}
{% load tz %}

<script src={% static 'js/myjs.js' %}></script>
<section>
  <div class="container">
    <h2 class="my-4" id="index-title">Project Miku</h2>
    <div class="row bg-secondary text-light my-2">
      <h5>Debug Info.</h5>
      <ul class="list-unstyled ps-4" id="debug1">
      </ul>
    </div>
    <button type="button" id="backInTable">now</button>
    <p id="tzname"></p>
    <script>
      var tzname = Intl.DateTimeFormat().resolvedOptions().timeZone;
      tznameobj = document.getElementById("tzname");
      tznameobj.innerText = "Timezone: " + tzname;
    </script>
    <div class="table-responsive timetable-container">
      <table class="table table-hover text-nowrap" id="timetable">
      </table>
    </div>
    <script src="{% static 'js/createTimetable.js' %}"></script>
    <div class="row" id="timetable2">
    </div>
    <script>
      const lesson_list = [];
      let lesson_slot;
      const timetable2 = document.getElementById('timetable2');
      {% for lesson in all_lessons %}
        try {
          const tmp_t = new Date('{{ lesson.time|date:"r" }}').getId();
          lesson_slot2 = document.getElementById(tmp_t);
          if(lesson_slot2 !== null){
            tmp_p = document.createElement('p');
            tmp_p.innerText = new Date('{{ lesson.time|date:"r" }}').getStr();
            tmp_p.innerText += ", Student: {{ lesson.student }}, Teacher: {{ lesson.teacher }}, booking: {{ lesson.booking }}";
            timetable2.appendChild(tmp_p);
            tmp_button = document.createElement('button');
            tmp_button.addEventListener("click", {scrollLeft: lesson_slot2.cellIndex, scrollDown: lesson_slot2.parentElement.rowIndex, handleEvent: scrollTable});
            tmp_button.type = 'button';
            tmp_button.textContent = "move";
            tmp_button.classList.add("mx-2");
            tmp_p.appendChild(tmp_button);
            const booking_text = {% if lesson.booking == True %}"closed";{% else %}"open";{% endif %}
            {% if request.user.is_authenticated %}
              {% if user == lesson.student %}
                const lesson_text = new Date('{{ lesson.time|date:"r" }}').getStr() + "Student is you. " + " Teacher: {{ lesson.teacher }}, " + booking_text;
                lesson_slot2.classList.add("bg-info");
              {% else %}
                const lesson_text = new Date('{{ lesson.time|date:"r" }}').getStr() + " Teacher: {{ lesson.teacher }}, " + booking_text;
              {% endif %}
            {% else %}
            const lesson_text = new Date('{{ lesson.time|date:"r" }}').getStr() + " Teacher: {{ lesson.teacher }}, " + booking_text;
            {% endif %}
            lesson_slot2.innerHTML = lesson_slot2.innerHTML + "<br />"+ lesson_text;
          }
        } catch(err) {
          const dbg2 =document.createElement('p');
          dbg2.innerText = err  + new Date('{{ lesson.time|date:"r" }}').getStr();
          timetable2.appendChild(dbg2);
        }
      {% endfor %}
    </script>
    <div class="row col-sm-4">
    <table class="table table-hover">
    <thead>
      <tr class="table-light"><th>Username</th><th>Email</th>
    </thead>
    {% if user.is_authenticated %}
      <tr><td>{{ user.username }}</td><td>{{ user.email }}</td></tr>
    {% else %}
      <tr><td>(guest)</td><td> - </td></tr>
    {% endif %}
    </table>
      <div>
      {{ general_date|date:"Y/m/j" }}
      </div>
      <div>
      {% localtime on %}
      <p>localtime on : {{ general_date|date:"r" }}</p>
      {% endlocaltime %}
      {% localtime off %}
      <p>localtime off : {{ general_date|date:"r" }}</p>
      <p> server localtime off: {{ CST_ex|date:"r" }}</p>
      <p id="dbgLocalTime"> CST2LT: </p>
      <script>
      var mytime1 = new Date('{{ CST_ex|date:"r" }}').getStr();
      var mytime2 = new Date('{{ CST_ex|date:"r" }}').getId();
      const dbgLocalTime = document.getElementById("dbgLocalTime");
      dbgLocalTime.innerText = dbgLocalTime.innerText + mytime1.toString();
      dbgLocalTime.innerText = dbgLocalTime.innerText + mytime2.toString();
      </script>
      {% endlocaltime %}
      </div>
    </div>
  </div>
</section>
<script src="{% static 'js/tableScroll.js' %}"></script>
{% endblock %}

miku/templates/inquiry.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans 'Inquiry' %}{% endblock %}
{% block content %}
<div class="container">
  <h2 class="my-4">{% trans  "Inquiry" %}</h2>
  <div class="row">
    <form method="post">
      {% csrf_token %}

      {{ form.non_field_errors }}

      {% for field in form %}
        <div class="row gx-2 mb-4">
          <label for="{{ field.id_for_label }}" class="col-md-3 col-form-label text-md-end">
            <strong>{{ field.label_tag }}</strong>
          </label>
          {% if field.id_for_label == "id_name" %}
          <div class="col-md-5">
            {{ field }}
            {{ field.errors }}
          </div>
          {% elif field.id_for_label == "id_email" %}
          <div class="col-md-7">
            {{ field }}
            {{ field.errors }}
          </div>
          {% else %}
          <div class="col-md-9">
            {{ field }}
            {{ field.errors }}
          </div>
          {% endif %}
        </div>
      {% endfor %}
      <div class="row">
        <div class="col-12 text-end">
          <button class="btn btn-primary" type="submit">{% trans "Send" %}</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

miku/templates/pagination.html
<ul class="pagination" style="justify-content:center">

  {% if page_obj.has_previous %}
  <li class="page-item">
    <a class="page-link"
      href="?page={{ page_obj.previous_page_number }}"
      aria-label="Previous">
    <span aria-hidden="true">&laquo;</span>
    </a>
  </li>
  {% endif %}

  {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
    <li class="page-item active">
      <span class="page-link">{{ num }}</span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ num }}">{{ num }}</a>
    </li>
    {% endif %}
  {% endfor %}

  {% if page_obj.has_next %}
  <li class="page-item">
    <a class="page-link"
      href="?page={{ page_obj.next_page_number }}"
      aria-label="Next">
    <span aria-hidden="true">&raquo;</span>
    </a>
  </li>
  {% endif %}
</ul>